<template>
  <div class="aligner h-screen">
    <div class="wrapper aligner bg-gray-100 shadow-lg rounded text-center">
      <h1 class="sm:text-xl text-lg font-bold">
        คุณได้ตอบแบบสอบถามเรียบร้อย
        <p class="text-lg font-normal text-gray-500">
          ขอขอบคุณสำหรับการตอบแบบสอบถาม
        </p>
        <p class="text-lg font-normal text-gray-500">
          ช้อปต่อที่
          <span><a href="https://shop.line.me">https://shop.line.me </a></span
          >เลย
        </p>
      </h1>
    </div>
  </div>
</template>

<script>
</script>
<style>
.wrapper {
  width: 500px;
  height: 300px;
}
.aligner {
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>